---
title: "ICD Tidy Tuesday"
author: "Some Tidy Tuesday Fun!"
output:
  prettydoc::html_pretty:
    theme: hpstr
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


# Tidy Tuesday Activities

Here are some Tidy Tuesday activities.

<br />

## February 01, 08, and 15, 2021

You will get a chance to re-create features from the bubble plot featured on Gapminder.org. You can also try adding emoji to a plot, using the `{ggtext}` package to make fancy titles and text, and try creating an animated plot!

- [Activity (HTML)](worksheets/tidy-tuesday-2021-02-01.html) [Updated 2021-02-02 to include links to the emoGG package]
- [RMD File](worksheets/tidy-tuesday-2021-02-01.Rmd)

The meeting on February 08 will be a working meeting where you can collaborate with others to on these problems. On February 15, you can share the plots you made with others as we celebrate your effort! 

<br />


## March, 2021

This month you will get a chance to re-create some of the charts, graphs, and maps presented at the 1900 Paris Exposition by sociologist and Black rights activist W. E. B. Du Bois.

- [Activity (HTML)](worksheets/tidy-tuesday-2021-03-01.html)
- [RMD File](worksheets/tidy-tuesday-2021-03-01.Rmd)

Each meeting in March will be a working meeting where you can work on re-creating these spelndid data portraits, collaborate with others, and workshop your ideas and plots. 

<br />

# About Us

The ICD Tidy Tuesday group is run and attended by a bunch of really smart graduate students, post-docs, and personnel from the [Institute of Child Development](https://icd.umn.edu/) at the University of Minnesota (with some help from Andy).

Inspired by the [Tidy Tuesday Social Data Project](https://thomasmock.netlify.app/post/tidytuesday-a-weekly-social-data-project-in-r/), the goal of this group is to promote members' computational skills, especially those for working with data. This group is about community, and we learn from each other. 



